name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:

    name: Python ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9']

    defaults:
      run:
        shell: bash -l {0}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt 

      - name: Install wagtail-openedx
        run: |
          pip install .

      - name: Pre-commit (linting)
        uses: pre-commit/action@v2.0.3

      - name: Test docs
        run: make -C ./docs html

      - name: Test code
        run: |
          coverage run --source wagtail_openedx runtests.py
          coverage xml -i
          coverage report -m

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
